FROM apache/airflow:2.7.1-python3.11

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow
RUN pip install --no-cache-dir \
    dbt-postgres \
    pandas \
    pyarrow \
    requests \
    boto3 \
    httpx \
    protobuf==4.25.3
